export TF_VAR_tenancy_ocid="ocid1.tenancy.oc1..aaaaaaaatj****************************************************"
export TF_VAR_compartment_ocid="ocid1.tenancy.oc1..aaaaaaaatj**************************************************"
export TF_VAR_user_ocid="ocid1.user.oc1..aaaaaaaaoi***************************************************"
export TF_VAR_fingerprint="fd:21:0a:c9:d3:**:**:**:**:**:**:**:**:**:**:**"
export TF_VAR_private_key_path="/vagrant-share/.oci-auth/oci_private_key"
export TF_VAR_region="us-phoenix-1"
